kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    exclude:
      - cron

steps:
- name: build
  image: quackerd/fedora:latest
  commands:
  - mkdir build
  - cd build
  - cmake ../
  - make

---
kind: pipeline
type: docker
name: docker-update

trigger:
  event:
    - cron
  cron:
    - nightly

steps:
  - name: docker-update
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quackerd/fedora
      tags: latest
