//-----------------------------------------------------------------------------
// File: kahalu_ddc_lib.c
// Author : Matthew Pumar<matpumar@microsoft.com>
// Generated on: 2016-06-27 12:44:57.886442
//-----------------------------------------------------------------------------
// Description : AUTOGENERATED CODE by ddc_timing.py DO NOT MODIFY
//                  
//-----------------------------------------------------------------------------
// Copyright (c) 2015 by Microsoft.
// This model is the confidential and proprietary property of Microsoft and the
// possession or use of this file requires a written license from Microsoft.
//-----------------------------------------------------------------------------

#ifndef _DDC_REG_C_
#define _DDC_REG_C_

#include <kahalu_sim_init.h>

int dram_type = -1;

void get_dram_type(){
    if(dram_type == -1){
        dram_type = 0;
    }
}   
lp3_ddc_params lp3_param_db = {
   .dqsck={2,5,5,0,5},
   .ppd={0,4,16,0,4},
   .rrd={4,8,20,0,8},
   .zqcs={68,72,84,0,72},
   .rank={2,5,17,0,5},
   .rfcab={164,168,180,0,168},
   .refi={3885,3890,3905,0,3890},
   .zqcl={284,288,300,0,288},
   .rtp={6,6,6,0,6},
   .dqsq={0,1,13,0,1},
   .dqss={0,2,14,0,2},
   .rfcpb={68,72,84,0,72},
   .rpab={13,17,29,0,17},
   .rcpb={44,48,60,0,48},
   .xpd={2,6,18,0,6},
   .rpst={0,1,13,0,1},
   .rcd={12,15,20,0,15},
   .xsr={170,174,186,0,174},
   .zqreset={36,40,52,0,40},
   .cke={2,6,18,0,6},
   .wtr={2,6,18,0,6},
   .wpre={0,1,13,0,1},
   .bl={0,0,0,0,0},
   .wl={6,6,6,0,6},
   .faw={36,40,52,0,40},
   .zqinit={796,800,812,0,800},
   .rl={12,12,12,0,12},
   .wr={12,12,12,0,12},
   .rcab={47,51,63,0,51},
   .rlat={6,14,22,0,14},
   .rppb={11,15,27,0,15},
   .sr={8,12,24,0,12},
   .mrri={16,20,32,0,20},
   .mrw={6,10,22,0,10},
   .mrr={0,4,16,0,4},
   .mrd={8,12,24,0,12},
   .ccd={4,8,20,0,8},
   .ras={30,34,46,0,34}
};

lp4_ddc_params lp4_param_db = {
   .dqsck={2,6,6,0,6,6},
   .ppd={4,4,4,0,4,4},
   .rrd={8,16,40,0,16,16},
   .dqs2dq={2,2,2,0,2,2},
   .rank={2,10,30,0,10,10},
   .rfcab={440,448,472,0,448,448},
   .refi={6242,6250,6274,0,6250,6247},
   .rtw={23,31,55,0,31,31},
   .rtp={12,12,12,0,12,12},
   .dqss={2,2,2,0,2,2},
   .rfcpb={216,224,248,0,224,224},
   .rpab={26,34,58,0,34,34},
   .zqlatch={40,48,72,0,48,48},
   .rcpb={80,97,144,0,97,97},
   .xpd={12,12,24,0,12,12},
   .ckelpd={4,12,36,0,12,12},
   .rpst={1,1,25,0,1,1},
   .rcd={21,29,53,0,29,29},
   .xsr={452,460,484,0,460,460},
   .ccdmw={24,32,56,0,32,32},
   .escke={2,2,2,0,2,3},
   .zqreset={72,80,104,0,80,80},
   .cke={4,12,24,0,12,12},
   .wtr={8,16,40,0,16,16},
   .rtrrd={43,51,75,0,51,51},
   .wpre={2,2,2,0,2,3},
   .bl={0,0,0,0,0,0},
   .mrwckel={15,23,47,0,23,23},
   .wl={14,14,14,0,14,14},
   .faw={56,64,88,0,64,64},
   .cmdcke={0,3,14,0,3,3},
   .rl={32,32,32,0,32,32},
   .wr={30,30,30,0,30,30},
   .ckesr={16,24,48,0,24,24},
   .zqinit={1592,1600,1624,0,1600,1600},
   .rcab={85,101,149,0,101,101},
   .rlat={0,6,30,0,6,6},
   .rppb={21,29,53,0,29,29},
   .wrwtr={20,28,52,0,28,28},
   .sr={16,24,48,0,24,24},
   .mrri={24,32,56,0,32,32},
   .mrw={8,16,31,0,16,16},
   .odtlon={6,6,6,0,6,6},
   .odton={2,2,2,0,2,2},
   .mrr={5,14,28,0,14,13},
   .mrd={15,23,31,0,23,23},
   .ccd={8,8,16,0,8,8},
   .ras={60,68,92,0,68,68}
};

#include <kahalu_frequency_lib.c>
    
void update_ddc_fields(const int mc, const int dram_frequency){
    
    uint32_t wdata, wmask, param1, param2, param3, param4, param5, param6, param7, param8, param9, param10, param11;      
    uint32_t mirror_needs_update = 0;
    
    hw_status("Entered update_ddc_fields\n");
    
    if(dram_type == -1){
        get_dram_type();
    }

    if(dram_type == 0){//LP3
        #ifdef MCU_IP_VERIF
        if(((param1= lp3_param_db.zqcl[DDC_PROG])!=lp3_param_db.zqcl[DDC_REG])|
               ((param2= lp3_param_db.zqinit[DDC_PROG])!=lp3_param_db.zqinit[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPR_0_ZQCLPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_0_ZQCLPR_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TPR_0_ZQINITPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_0_ZQINITPR_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPR_0_ZQCLPR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPR_0_ZQINITPR_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpr_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.zqreset[DDC_PROG])!=lp3_param_db.zqreset[DDC_REG])|
               ((param2= lp3_param_db.zqcs[DDC_PROG])!=lp3_param_db.zqcs[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPR_1_ZQRESETPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_1_ZQRESETPR_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TPR_1_ZQCSPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_1_ZQCSPR_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPR_1_ZQRESETPR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPR_1_ZQCSPR_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpr_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.rl[DDC_PROG])!=lp3_param_db.rl[DDC_REG])|
               ((param2= lp3_param_db.dqsck[DDC_PROG])!=lp3_param_db.dqsck[DDC_REG])|
               ((param3= lp3_param_db.bl[DDC_PROG])!=lp3_param_db.bl[DDC_REG])|
               ((param4= lp3_param_db.xpd[DDC_PROG])!=lp3_param_db.xpd[DDC_REG])|
               ((param5= lp3_param_db.mrri[DDC_PROG])!=lp3_param_db.mrri[DDC_REG])|
               ((param6= lp3_param_db.wl[DDC_PROG])!=lp3_param_db.wl[DDC_REG])|
               ((param7= lp3_param_db.rpab[DDC_PROG])!=lp3_param_db.rpab[DDC_REG])){
        #endif
            wdata =  (((param1+param2+param3/2+1)                         
                        <<(uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_FIELD_MASK);
            wdata |= (((param4+param5)                         
                        <<(uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_FIELD_MASK);
            wdata |= (((param1+param2+param3/2+1-param6)                         
                        <<(uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_WL_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_WL_FIELD_MASK);
            wdata |= (((param7)                         
                        <<(uint32_t)DDC_REGS_TAB_4_RPAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_RPAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_WL_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_4_RPAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_4), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.rcd[DDC_PROG])!=lp3_param_db.rcd[DDC_REG])|
               ((param2= lp3_param_db.wl[DDC_PROG])!=lp3_param_db.wl[DDC_REG])|
               ((param3= lp3_param_db.bl[DDC_PROG])!=lp3_param_db.bl[DDC_REG])|
               ((param4= lp3_param_db.wr[DDC_PROG])!=lp3_param_db.wr[DDC_REG])|
               ((param5= lp3_param_db.rppb[DDC_PROG])!=lp3_param_db.rppb[DDC_REG])|
               ((param6= lp3_param_db.ras[DDC_PROG])!=lp3_param_db.ras[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPB_0_RCDPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_RCDPB_FIELD_MASK);
            wdata |= (((param2+param3/2+param4+1)                         
                        <<(uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_FIELD_MASK);
            wdata |= (((param2+param3/2+param4+1+param5)                         
                        <<(uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_FIELD_MASK);
            wdata |= (((param6)                         
                        <<(uint32_t)DDC_REGS_TPB_0_RASPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_RASPB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_0_RCDPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_RASPB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.rank[DDC_PROG])!=lp3_param_db.rank[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RANKAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_5), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.rcpb[DDC_PROG])!=lp3_param_db.rcpb[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPB_3_RCPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_3_RCPB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_3_RCPB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_3), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.mrw[DDC_PROG])!=lp3_param_db.mrw[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_7_MRWAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_7_MRWAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_7_MRWAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_7), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.rppb[DDC_PROG])!=lp3_param_db.rppb[DDC_REG])|
               ((param2= lp3_param_db.bl[DDC_PROG])!=lp3_param_db.bl[DDC_REG])|
               ((param3= lp3_param_db.rtp[DDC_PROG])!=lp3_param_db.rtp[DDC_REG])|
               ((param4= lp3_param_db.rfcpb[DDC_PROG])!=lp3_param_db.rfcpb[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RPPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RPPB_FIELD_MASK);
            wdata |= (((param2/2+((4>param3)?4:param3)-4)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RFCPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RFCPB_FIELD_MASK);
            wdata |= (((param2/2+((4>param3)?4:param3)-4+param1)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_RPPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_RPPB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_1_RPPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_1_RFCPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_1_RTPPB_M4_BLDIV2_RPPB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.wl[DDC_PROG])!=lp3_param_db.wl[DDC_REG])|
               ((param2= lp3_param_db.bl[DDC_PROG])!=lp3_param_db.bl[DDC_REG])|
               ((param3= lp3_param_db.wtr[DDC_PROG])!=lp3_param_db.wtr[DDC_REG])|
               ((param4= lp3_param_db.sr[DDC_PROG])!=lp3_param_db.sr[DDC_REG])){
        #endif
            wdata =  (((param1+1+param2/2+param3)                         
                        <<(uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_LSB)
                       &  (uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TAB_1_SRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_1_SRAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_1_SRAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.xpd[DDC_PROG])!=lp3_param_db.xpd[DDC_REG])|
               ((param2= lp3_param_db.mrd[DDC_PROG])!=lp3_param_db.mrd[DDC_REG])|
               ((param3= lp3_param_db.rrd[DDC_PROG])!=lp3_param_db.rrd[DDC_REG])|
               ((param4= lp3_param_db.mrr[DDC_PROG])!=lp3_param_db.mrr[DDC_REG])|
               ((param5= lp3_param_db.cke[DDC_PROG])!=lp3_param_db.cke[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_0_XPDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_XPDAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_0_MRDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_MRDAB_FIELD_MASK);
            wdata |= (((param3)                         
                        <<(uint32_t)DDC_REGS_TAB_0_RRDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_RRDAB_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TAB_0_MRRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_MRRAB_FIELD_MASK);
            wdata |= (((param5)                         
                        <<(uint32_t)DDC_REGS_TAB_0_CKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_CKEAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_0_XPDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_MRDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_RRDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_MRRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_CKEAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.wl[DDC_PROG])!=lp3_param_db.wl[DDC_REG])|
               ((param2= lp3_param_db.rl[DDC_PROG])!=lp3_param_db.rl[DDC_REG])|
               ((param3= lp3_param_db.rlat[DDC_PROG])!=lp3_param_db.rlat[DDC_REG])|
               ((param4= lp3_param_db.faw[DDC_PROG])!=lp3_param_db.faw[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_3_WLAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_WLAB_FIELD_MASK);
            wdata |= (((param2+param3)                         
                        <<(uint32_t)DDC_REGS_TAB_3_RL_RLATAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_RL_RLATAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_3_RLAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_RLAB_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TAB_3_FAWAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_FAWAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_3_WLAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_RL_RLATAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_RLAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_FAWAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_3), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        if(((param1= lp3_param_db.xsr[DDC_PROG])!=lp3_param_db.xsr[DDC_REG])|
               ((param2= lp3_param_db.rfcab[DDC_PROG])!=lp3_param_db.rfcab[DDC_REG])){
        #endif
            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_2_XSRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_2_XSRAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_2_RFCAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_2_RFCAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_2_XSRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_2_RFCAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_2), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        }
        #endif
    }else{//LP4

        if(dram_frequency != 400){

        if(((param1= lp4_param_db.escke[DDC_PROG])!=lp4_param_db.escke[DDC_REG])|
               ((param2= lp4_param_db.cmdcke[DDC_PROG])!=lp4_param_db.cmdcke[DDC_REG])|
               ((param3= lp4_param_db.rtp[DDC_PROG])!=lp4_param_db.rtp[DDC_REG])|
               ((param4= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param5= lp4_param_db.dqsck[DDC_PROG])!=lp4_param_db.dqsck[DDC_REG])|
               ((param6= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param7= lp4_param_db.rpst[DDC_PROG])!=lp4_param_db.rpst[DDC_REG])|
               ((param8= lp4_param_db.odtlon[DDC_PROG])!=lp4_param_db.odtlon[DDC_REG])|
               ((param9= lp4_param_db.odton[DDC_PROG])!=lp4_param_db.odton[DDC_REG])|
               ((param10= lp4_param_db.rank[DDC_PROG])!=lp4_param_db.rank[DDC_REG])|
               ((param11= lp4_param_db.mrwckel[DDC_PROG])!=lp4_param_db.mrwckel[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_5_ESCKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_ESCKEAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_5_CMDCKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_CMDCKEAB_FIELD_MASK);
            wdata |= (((param3)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RTPAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RTPAB_FIELD_MASK);
            wdata |= (((param4+param5+param6/2+param7-param8-param9+2)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_FIELD_MASK);
            wdata |= (((param10)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RANKAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK);
            wdata |= (((param11)                         
                        <<(uint32_t)DDC_REGS_TAB_5_MRWCKELAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_MRWCKELAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_5_ESCKEAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_CMDCKEAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RTPAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_MRWCKELAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_5), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        }else{
        if(((param1= lp4_param_db.escke[DDC_PROG])!=lp4_param_db.escke[DDC_REG])|
               ((param2= lp4_param_db.cmdcke[DDC_PROG])!=lp4_param_db.cmdcke[DDC_REG])|
               ((param3= lp4_param_db.rtp[DDC_PROG])!=lp4_param_db.rtp[DDC_REG])|
               ((param4= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param5= lp4_param_db.dqsck[DDC_PROG])!=lp4_param_db.dqsck[DDC_REG])|
               ((param6= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param7= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param8= lp4_param_db.wpre[DDC_PROG])!=lp4_param_db.wpre[DDC_REG])|
               ((param9= lp4_param_db.rpst[DDC_PROG])!=lp4_param_db.rpst[DDC_REG])|
               ((param10= lp4_param_db.rank[DDC_PROG])!=lp4_param_db.rank[DDC_REG])|
               ((param11= lp4_param_db.mrwckel[DDC_PROG])!=lp4_param_db.mrwckel[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_5_ESCKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_ESCKEAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_5_CMDCKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_CMDCKEAB_FIELD_MASK);
            wdata |= (((param3)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RTPAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RTPAB_FIELD_MASK);
            wdata |= (((param4+param5+param6/2-param7+param8+param9)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_FIELD_MASK);
            wdata |= (((param10)                         
                        <<(uint32_t)DDC_REGS_TAB_5_RANKAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK);
            wdata |= (((param11)                         
                        <<(uint32_t)DDC_REGS_TAB_5_MRWCKELAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_5_MRWCKELAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_5_ESCKEAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_CMDCKEAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RTPAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RL_DQSCK_BLDIV2_WPRE_WL_RPST_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_RANKAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_5_MRWCKELAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_5), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        }

        if(((param1= lp4_param_db.zqinit[DDC_PROG])!=lp4_param_db.zqinit[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPR_0_ZQINITPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_0_ZQINITPR_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPR_0_ZQINITPR_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpr_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.zqreset[DDC_PROG])!=lp4_param_db.zqreset[DDC_REG])|
               ((param2= lp4_param_db.zqlatch[DDC_PROG])!=lp4_param_db.zqlatch[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPR_1_ZQRESETPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_1_ZQRESETPR_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TPR_1_ZQLATCHPR_LSB)
                       &  (uint32_t)DDC_REGS_TPR_1_ZQLATCHPR_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPR_1_ZQRESETPR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPR_1_ZQLATCHPR_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpr_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param2= lp4_param_db.dqss[DDC_PROG])!=lp4_param_db.dqss[DDC_REG])|
               ((param3= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param4= lp4_param_db.wtr[DDC_PROG])!=lp4_param_db.wtr[DDC_REG])|
               ((param5= lp4_param_db.rtw[DDC_PROG])!=lp4_param_db.rtw[DDC_REG])|
               ((param6= lp4_param_db.wrwtr[DDC_PROG])!=lp4_param_db.wrwtr[DDC_REG])|
               ((param7= lp4_param_db.rtrrd[DDC_PROG])!=lp4_param_db.rtrrd[DDC_REG])){

            wdata =  (((param1+param2+param3/2+param4)                         
                        <<(uint32_t)DDC_REGS_TAB_6_WL_DQSS_BLDIV2_WTRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_6_WL_DQSS_BLDIV2_WTRAB_FIELD_MASK);
            wdata |= (((param5)                         
                        <<(uint32_t)DDC_REGS_TAB_6_RTWAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_6_RTWAB_FIELD_MASK);
            wdata |= (((param6)                         
                        <<(uint32_t)DDC_REGS_TAB_6_WRWTRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_6_WRWTRAB_FIELD_MASK);
            wdata |= (((param7)                         
                        <<(uint32_t)DDC_REGS_TAB_6_RTRRDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_6_RTRRDAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_6_WL_DQSS_BLDIV2_WTRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_6_RTWAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_6_WRWTRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_6_RTRRDAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_6), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param2= lp4_param_db.dqsck[DDC_PROG])!=lp4_param_db.dqsck[DDC_REG])|
               ((param3= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param4= lp4_param_db.xpd[DDC_PROG])!=lp4_param_db.xpd[DDC_REG])|
               ((param5= lp4_param_db.mrri[DDC_PROG])!=lp4_param_db.mrri[DDC_REG])|
               ((param6= lp4_param_db.rpab[DDC_PROG])!=lp4_param_db.rpab[DDC_REG])){

            wdata =  (((param1+param2+param3/2+1)                         
                        <<(uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_FIELD_MASK);
            wdata |= (((param4+param5)                         
                        <<(uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_FIELD_MASK);
            wdata |= (((param6)                         
                        <<(uint32_t)DDC_REGS_TAB_4_RPAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_4_RPAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_4_RL_DQSCK_P1_BLDIV2_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_4_XPD_MRRIAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_4_RPAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_4), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.rcpb[DDC_PROG])!=lp4_param_db.rcpb[DDC_REG])|
               ((param2= lp4_param_db.rtp[DDC_PROG])!=lp4_param_db.rtp[DDC_REG])|
               ((param3= lp4_param_db.rppb[DDC_PROG])!=lp4_param_db.rppb[DDC_REG])){

            wdata =  (((param1+6)                         
                        <<(uint32_t)DDC_REGS_TDERATE_2_RCPB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_2_RCPB_DERATED_FIELD_MASK);
            wdata |= (((param2+param3+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_2_RTPPB_RPPB_P8_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_2_RTPPB_RPPB_P8_DERATED_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TDERATE_2_RCPB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_2_RTPPB_RPPB_P8_DERATED_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tderate_2), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.mrw[DDC_PROG])!=lp4_param_db.mrw[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_7_MRWAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_7_MRWAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_7_MRWAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_7), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(dram_frequency != 400){

        if(((param1= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param2= lp4_param_db.dqsck[DDC_PROG])!=lp4_param_db.dqsck[DDC_REG])|
               ((param3= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param4= lp4_param_db.rrd[DDC_PROG])!=lp4_param_db.rrd[DDC_REG])|
               ((param5= lp4_param_db.rpst[DDC_PROG])!=lp4_param_db.rpst[DDC_REG])|
               ((param6= lp4_param_db.odtlon[DDC_PROG])!=lp4_param_db.odtlon[DDC_REG])|
               ((param7= lp4_param_db.odton[DDC_PROG])!=lp4_param_db.odton[DDC_REG])|
               ((param8= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])){

            wdata =  (((param1+param2+param3/2+1+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_FIELD_MASK);
            wdata |= (((param4+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_FIELD_MASK);
            wdata |= (((param1+param2+param3/2+param5-param6-param7+2+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_FIELD_MASK);
            wdata |= (((param1+param2+param3/2+1-param8+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tderate_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        }else{
        if(((param1= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param2= lp4_param_db.dqsck[DDC_PROG])!=lp4_param_db.dqsck[DDC_REG])|
               ((param3= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param4= lp4_param_db.rrd[DDC_PROG])!=lp4_param_db.rrd[DDC_REG])|
               ((param5= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param6= lp4_param_db.wpre[DDC_PROG])!=lp4_param_db.wpre[DDC_REG])|
               ((param7= lp4_param_db.rpst[DDC_PROG])!=lp4_param_db.rpst[DDC_REG])){

            wdata =  (((param1+param2+param3/2+1+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_FIELD_MASK);
            wdata |= (((param4+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_FIELD_MASK);
            wdata |= (((param1+param2+param3/2-param5+param6+param7+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_FIELD_MASK);
            wdata |= (((param1+param2+param3/2+1-param5+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RRDAB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_BLDIV2_WPRE_WL_RPST_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_1_RL_DQSCK_P1_BLDIV2_WL_DERATED_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tderate_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        }        

        if(((param1= lp4_param_db.rppb[DDC_PROG])!=lp4_param_db.rppb[DDC_REG])|
               ((param2= lp4_param_db.rcd[DDC_PROG])!=lp4_param_db.rcd[DDC_REG])|
               ((param3= lp4_param_db.ras[DDC_PROG])!=lp4_param_db.ras[DDC_REG])|
               ((param4= lp4_param_db.rpab[DDC_PROG])!=lp4_param_db.rpab[DDC_REG])){

            wdata =  (((param1+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_0_RPPB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_0_RPPB_DERATED_FIELD_MASK);
            wdata |= (((param2+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_0_RCDPB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_0_RCDPB_DERATED_FIELD_MASK);
            wdata |= (((param3+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_0_RASPB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_0_RASPB_DERATED_FIELD_MASK);
            wdata |= (((param4+3)                         
                        <<(uint32_t)DDC_REGS_TDERATE_0_RPAB_DERATED_LSB)
                       &  (uint32_t)DDC_REGS_TDERATE_0_RPAB_DERATED_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TDERATE_0_RPPB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_0_RCDPB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_0_RASPB_DERATED_FIELD_MASK|
                    (uint32_t)DDC_REGS_TDERATE_0_RPAB_DERATED_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tderate_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param2= lp4_param_db.dqss[DDC_PROG])!=lp4_param_db.dqss[DDC_REG])|
               ((param3= lp4_param_db.dqs2dq[DDC_PROG])!=lp4_param_db.dqs2dq[DDC_REG])|
               ((param4= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param5= lp4_param_db.wr[DDC_PROG])!=lp4_param_db.wr[DDC_REG])|
               ((param6= lp4_param_db.rtp[DDC_PROG])!=lp4_param_db.rtp[DDC_REG])|
               ((param7= lp4_param_db.rppb[DDC_PROG])!=lp4_param_db.rppb[DDC_REG])|
               ((param8= lp4_param_db.ccdmw[DDC_PROG])!=lp4_param_db.ccdmw[DDC_REG])){

            wdata =  (((param1+param2+param3+param4/2+param5)                         
                        <<(uint32_t)DDC_REGS_TPB_2_WL_DQSS_DQS2DQ_BLDIV2_WR_LSB)
                       &  (uint32_t)DDC_REGS_TPB_2_WL_DQSS_DQS2DQ_BLDIV2_WR_FIELD_MASK);
            wdata |= (((param6+param7+0)                         
                        <<(uint32_t)DDC_REGS_TPB_2_RTPPB_RPPB_P8_LSB)
                       &  (uint32_t)DDC_REGS_TPB_2_RTPPB_RPPB_P8_FIELD_MASK);
            wdata |= (((param8)                         
                        <<(uint32_t)DDC_REGS_TPB_2_CCDMW_LSB)
                       &  (uint32_t)DDC_REGS_TPB_2_CCDMW_FIELD_MASK);
            wdata |= (((param4/2+((8>param6)?8:param6)-8)                         
                        <<(uint32_t)DDC_REGS_TPB_2_RTPPB_M8_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TPB_2_RTPPB_M8_BLDIV2_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_2_WL_DQSS_DQS2DQ_BLDIV2_WR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_2_RTPPB_RPPB_P8_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_2_CCDMW_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_2_RTPPB_M8_BLDIV2_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_2), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.rcpb[DDC_PROG])!=(lp4_param_db.rcpb[DDC_REG]+2))|
               ((param2= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param3= lp4_param_db.dqss[DDC_PROG])!=lp4_param_db.dqss[DDC_REG])|
               ((param4= lp4_param_db.dqs2dq[DDC_PROG])!=lp4_param_db.dqs2dq[DDC_REG])|
               ((param5= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param6= lp4_param_db.wr[DDC_PROG])!=lp4_param_db.wr[DDC_REG])){

            wdata =  (((param1+2)                         
                        <<(uint32_t)DDC_REGS_TPB_3_RCPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_3_RCPB_FIELD_MASK);
            wdata |= (((param2+param3+param4+param5/2+param6+2)                         
                        <<(uint32_t)DDC_REGS_TPB_3_WL_DQSS_DQS2DQ_BLDIV2_WR_P2_LSB)
                       &  (uint32_t)DDC_REGS_TPB_3_WL_DQSS_DQS2DQ_BLDIV2_WR_P2_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_3_RCPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_3_WL_DQSS_DQS2DQ_BLDIV2_WR_P2_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_3), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.rcd[DDC_PROG])!=lp4_param_db.rcd[DDC_REG])|
               ((param2= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param3= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param4= lp4_param_db.wr[DDC_PROG])!=lp4_param_db.wr[DDC_REG])|
               ((param5= lp4_param_db.rppb[DDC_PROG])!=lp4_param_db.rppb[DDC_REG])|
               ((param6= lp4_param_db.ras[DDC_PROG])!=lp4_param_db.ras[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPB_0_RCDPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_RCDPB_FIELD_MASK);
            wdata |= (((param2+param3/2+param4+1)                         
                        <<(uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_FIELD_MASK);
            wdata |= (((param2+param3/2+param4+1+param5)                         
                        <<(uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_FIELD_MASK);
            wdata |= (((param6)                         
                        <<(uint32_t)DDC_REGS_TPB_0_RASPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_0_RASPB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_0_RCDPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_WL_WRPB_P1_BLDIV2_RPPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_0_RASPB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.rppb[DDC_PROG])!=lp4_param_db.rppb[DDC_REG])|
               ((param2= lp4_param_db.rfcpb[DDC_PROG])!=lp4_param_db.rfcpb[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RPPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RPPB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TPB_1_RFCPB_LSB)
                       &  (uint32_t)DDC_REGS_TPB_1_RFCPB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TPB_1_RPPB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TPB_1_RFCPB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tpb_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param2= lp4_param_db.bl[DDC_PROG])!=lp4_param_db.bl[DDC_REG])|
               ((param3= lp4_param_db.wtr[DDC_PROG])!=lp4_param_db.wtr[DDC_REG])|
               ((param4= lp4_param_db.sr[DDC_PROG])!=lp4_param_db.sr[DDC_REG])){

            wdata =  (((param1+1+param2/2+param3)                         
                        <<(uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_LSB)
                       &  (uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TAB_1_SRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_1_SRAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_1_WL_P1_BLDIV2_WTR_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_1_SRAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_1), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.xpd[DDC_PROG])!=lp4_param_db.xpd[DDC_REG])|
               ((param2= lp4_param_db.mrd[DDC_PROG])!=lp4_param_db.mrd[DDC_REG])|
               ((param3= lp4_param_db.rrd[DDC_PROG])!=lp4_param_db.rrd[DDC_REG])|
               ((param4= lp4_param_db.mrr[DDC_PROG])!=lp4_param_db.mrr[DDC_REG])|
               ((param5= lp4_param_db.cke[DDC_PROG])!=lp4_param_db.cke[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_0_XPDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_XPDAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_0_MRDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_MRDAB_FIELD_MASK);
            wdata |= (((param3)                         
                        <<(uint32_t)DDC_REGS_TAB_0_RRDAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_RRDAB_FIELD_MASK);
            wdata |= (((param4/2)                         
                        <<(uint32_t)DDC_REGS_TAB_0_MRRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_MRRAB_FIELD_MASK);
            wdata |= (((param5/2)                         
                        <<(uint32_t)DDC_REGS_TAB_0_CKEAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_0_CKEAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_0_XPDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_MRDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_RRDAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_MRRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_0_CKEAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_0), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.wl[DDC_PROG])!=lp4_param_db.wl[DDC_REG])|
               ((param2= lp4_param_db.rl[DDC_PROG])!=lp4_param_db.rl[DDC_REG])|
               ((param3= lp4_param_db.rlat[DDC_PROG])!=lp4_param_db.rlat[DDC_REG])|
               ((param4= lp4_param_db.faw[DDC_PROG])!=lp4_param_db.faw[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_3_WLAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_WLAB_FIELD_MASK);
            wdata |= (((param2+param3)                         
                        <<(uint32_t)DDC_REGS_TAB_3_RL_RLATAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_RL_RLATAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_3_RLAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_RLAB_FIELD_MASK);
            wdata |= (((param4)                         
                        <<(uint32_t)DDC_REGS_TAB_3_FAWAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_3_FAWAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_3_WLAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_RL_RLATAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_RLAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_3_FAWAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_3), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
        if(((param1= lp4_param_db.xsr[DDC_PROG])!=lp4_param_db.xsr[DDC_REG])|
               ((param2= lp4_param_db.rfcab[DDC_PROG])!=lp4_param_db.rfcab[DDC_REG])){

            wdata =  (((param1)                         
                        <<(uint32_t)DDC_REGS_TAB_2_XSRAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_2_XSRAB_FIELD_MASK);
            wdata |= (((param2)                         
                        <<(uint32_t)DDC_REGS_TAB_2_RFCAB_LSB)
                       &  (uint32_t)DDC_REGS_TAB_2_RFCAB_FIELD_MASK);
            wmask = (uint32_t)DDC_REGS_TAB_2_XSRAB_FIELD_MASK|
                    (uint32_t)DDC_REGS_TAB_2_RFCAB_FIELD_MASK;
            set_reg_val(mc, (uintptr_t)&(chip_regs->ddc_regs.tab_2), wmask, wdata);
        #ifdef MCU_IP_VERIF
            mirror_needs_update=1;
        #endif
        }
    }
    #ifdef MCU_IP_VERIF
    if(mirror_needs_update){
        update_all_ddc_param(mc, DDC_PROG, dram_frequency);
    }
    #endif
    hw_status("Exiting update_ddc_fields\n");
}

void update_all_ddc_param(const int mc, int val, const int dram_frequency){

    uint32_t l_index;
       
    if(val == -1){
        return;
    }

    if(dram_type == -1){
         get_dram_type();
    }
   
    if((val == DDC_MIN) || (val == DDC_TYP) || (val == DDC_MAX) || (val == DDC_PROG) || (val == DDC_MICRON)){
        
        if(val == DDC_PROG){
            l_index = DDC_REG;
        }else{
            l_index = DDC_PROG;
        }
        
        if(dram_type == 0){//LP3
           lp3_param_db.dqsck[l_index] = lp3_param_db.dqsck[val];
           lp3_param_db.ppd[l_index] = lp3_param_db.ppd[val];
           lp3_param_db.rrd[l_index] = lp3_param_db.rrd[val];
           lp3_param_db.zqcs[l_index] = lp3_param_db.zqcs[val];
           lp3_param_db.rank[l_index] = lp3_param_db.rank[val];
           lp3_param_db.rfcab[l_index] = lp3_param_db.rfcab[val];
           lp3_param_db.refi[l_index] = lp3_param_db.refi[val];
           lp3_param_db.zqcl[l_index] = lp3_param_db.zqcl[val];
           lp3_param_db.rtp[l_index] = lp3_param_db.rtp[val];
           lp3_param_db.dqsq[l_index] = lp3_param_db.dqsq[val];
           lp3_param_db.dqss[l_index] = lp3_param_db.dqss[val];
           lp3_param_db.rfcpb[l_index] = lp3_param_db.rfcpb[val];
           lp3_param_db.rpab[l_index] = lp3_param_db.rpab[val];
           lp3_param_db.rcpb[l_index] = lp3_param_db.rcpb[val];
           lp3_param_db.xpd[l_index] = lp3_param_db.xpd[val];
           lp3_param_db.rpst[l_index] = lp3_param_db.rpst[val];
           lp3_param_db.rcd[l_index] = lp3_param_db.rcd[val];
           lp3_param_db.xsr[l_index] = lp3_param_db.xsr[val];
           lp3_param_db.zqreset[l_index] = lp3_param_db.zqreset[val];
           lp3_param_db.cke[l_index] = lp3_param_db.cke[val];
           lp3_param_db.wtr[l_index] = lp3_param_db.wtr[val];
           lp3_param_db.wpre[l_index] = lp3_param_db.wpre[val];
           lp3_param_db.bl[l_index] = lp3_param_db.bl[val];
           lp3_param_db.wl[l_index] = lp3_param_db.wl[val];
           lp3_param_db.faw[l_index] = lp3_param_db.faw[val];
           lp3_param_db.zqinit[l_index] = lp3_param_db.zqinit[val];
           lp3_param_db.rl[l_index] = lp3_param_db.rl[val];
           lp3_param_db.wr[l_index] = lp3_param_db.wr[val];
           lp3_param_db.rcab[l_index] = lp3_param_db.rcab[val];
           lp3_param_db.rlat[l_index] = lp3_param_db.rlat[val];
           lp3_param_db.rppb[l_index] = lp3_param_db.rppb[val];
           lp3_param_db.sr[l_index] = lp3_param_db.sr[val];
           lp3_param_db.mrri[l_index] = lp3_param_db.mrri[val];
           lp3_param_db.mrw[l_index] = lp3_param_db.mrw[val];
           lp3_param_db.mrr[l_index] = lp3_param_db.mrr[val];
           lp3_param_db.mrd[l_index] = lp3_param_db.mrd[val];
           lp3_param_db.ccd[l_index] = lp3_param_db.ccd[val];
           lp3_param_db.ras[l_index] = lp3_param_db.ras[val];
       }else{//LP4
           lp4_param_db.dqsck[l_index] = lp4_param_db.dqsck[val];
           lp4_param_db.ppd[l_index] = lp4_param_db.ppd[val];
           lp4_param_db.rrd[l_index] = lp4_param_db.rrd[val];
           lp4_param_db.dqs2dq[l_index] = lp4_param_db.dqs2dq[val];
           lp4_param_db.rank[l_index] = lp4_param_db.rank[val];
           lp4_param_db.rfcab[l_index] = lp4_param_db.rfcab[val];
           lp4_param_db.refi[l_index] = lp4_param_db.refi[val];
           lp4_param_db.rtw[l_index] = lp4_param_db.rtw[val];
           lp4_param_db.rtp[l_index] = lp4_param_db.rtp[val];
           lp4_param_db.dqss[l_index] = lp4_param_db.dqss[val];
           lp4_param_db.rfcpb[l_index] = lp4_param_db.rfcpb[val];
           lp4_param_db.rpab[l_index] = lp4_param_db.rpab[val];
           lp4_param_db.zqlatch[l_index] = lp4_param_db.zqlatch[val];
           lp4_param_db.rcpb[l_index] = lp4_param_db.rcpb[val];
           lp4_param_db.xpd[l_index] = lp4_param_db.xpd[val];
           lp4_param_db.ckelpd[l_index] = lp4_param_db.ckelpd[val];
           lp4_param_db.rpst[l_index] = lp4_param_db.rpst[val];
           lp4_param_db.rcd[l_index] = lp4_param_db.rcd[val];
           lp4_param_db.xsr[l_index] = lp4_param_db.xsr[val];
           lp4_param_db.ccdmw[l_index] = lp4_param_db.ccdmw[val];
           lp4_param_db.escke[l_index] = lp4_param_db.escke[val];
           lp4_param_db.zqreset[l_index] = lp4_param_db.zqreset[val];
           lp4_param_db.cke[l_index] = lp4_param_db.cke[val];
           lp4_param_db.wtr[l_index] = lp4_param_db.wtr[val];
           lp4_param_db.rtrrd[l_index] = lp4_param_db.rtrrd[val];
           lp4_param_db.wpre[l_index] = lp4_param_db.wpre[val];
           lp4_param_db.bl[l_index] = lp4_param_db.bl[val];
           lp4_param_db.mrwckel[l_index] = lp4_param_db.mrwckel[val];
           lp4_param_db.wl[l_index] = lp4_param_db.wl[val];
           lp4_param_db.faw[l_index] = lp4_param_db.faw[val];
           lp4_param_db.cmdcke[l_index] = lp4_param_db.cmdcke[val];
           lp4_param_db.rl[l_index] = lp4_param_db.rl[val];
           lp4_param_db.wr[l_index] = lp4_param_db.wr[val];
           lp4_param_db.ckesr[l_index] = lp4_param_db.ckesr[val];
           lp4_param_db.zqinit[l_index] = lp4_param_db.zqinit[val];
           lp4_param_db.rcab[l_index] = lp4_param_db.rcab[val];
           lp4_param_db.rlat[l_index] = lp4_param_db.rlat[val];
           lp4_param_db.rppb[l_index] = lp4_param_db.rppb[val];
           lp4_param_db.wrwtr[l_index] = lp4_param_db.wrwtr[val];
           lp4_param_db.sr[l_index] = lp4_param_db.sr[val];
           lp4_param_db.mrri[l_index] = lp4_param_db.mrri[val];
           lp4_param_db.mrw[l_index] = lp4_param_db.mrw[val];
           lp4_param_db.odtlon[l_index] = lp4_param_db.odtlon[val];
           lp4_param_db.odton[l_index] = lp4_param_db.odton[val];
           lp4_param_db.mrr[l_index] = lp4_param_db.mrr[val];
           lp4_param_db.mrd[l_index] = lp4_param_db.mrd[val];
           lp4_param_db.ccd[l_index] = lp4_param_db.ccd[val];
           lp4_param_db.ras[l_index] = lp4_param_db.ras[val];
       }
    }else if(val== DDC_RAND){
        if(dram_type == 0){//LP3
            lp3_param_db.dqsck[DDC_PROG] = getRandInterval(lp3_param_db.dqsck[DDC_MIN],lp3_param_db.dqsck[DDC_MAX]);
            lp3_param_db.ppd[DDC_PROG] = getRandInterval(lp3_param_db.ppd[DDC_MIN],lp3_param_db.ppd[DDC_MAX]);
            lp3_param_db.rrd[DDC_PROG] = getRandInterval(lp3_param_db.rrd[DDC_MIN],lp3_param_db.rrd[DDC_MAX]);
            lp3_param_db.zqcs[DDC_PROG] = getRandInterval(lp3_param_db.zqcs[DDC_MIN],lp3_param_db.zqcs[DDC_MAX]);
            lp3_param_db.rank[DDC_PROG] = getRandInterval(lp3_param_db.rank[DDC_MIN],lp3_param_db.rank[DDC_MAX]);
            lp3_param_db.rfcab[DDC_PROG] = getRandInterval(lp3_param_db.rfcab[DDC_MIN],lp3_param_db.rfcab[DDC_MAX]);
            lp3_param_db.refi[DDC_PROG] = getRandInterval(lp3_param_db.refi[DDC_MIN],lp3_param_db.refi[DDC_MAX]);
            lp3_param_db.zqcl[DDC_PROG] = getRandInterval(lp3_param_db.zqcl[DDC_MIN],lp3_param_db.zqcl[DDC_MAX]);
            lp3_param_db.rtp[DDC_PROG] = getRandInterval(lp3_param_db.rtp[DDC_MIN],lp3_param_db.rtp[DDC_MAX]);
            lp3_param_db.dqsq[DDC_PROG] = getRandInterval(lp3_param_db.dqsq[DDC_MIN],lp3_param_db.dqsq[DDC_MAX]);
            lp3_param_db.dqss[DDC_PROG] = getRandInterval(lp3_param_db.dqss[DDC_MIN],lp3_param_db.dqss[DDC_MAX]);
            lp3_param_db.rfcpb[DDC_PROG] = getRandInterval(lp3_param_db.rfcpb[DDC_MIN],lp3_param_db.rfcpb[DDC_MAX]);
            lp3_param_db.rpab[DDC_PROG] = getRandInterval(lp3_param_db.rpab[DDC_MIN],lp3_param_db.rpab[DDC_MAX]);
            lp3_param_db.rcpb[DDC_PROG] = getRandInterval(lp3_param_db.rcpb[DDC_MIN],lp3_param_db.rcpb[DDC_MAX]);
            lp3_param_db.xpd[DDC_PROG] = getRandInterval(lp3_param_db.xpd[DDC_MIN],lp3_param_db.xpd[DDC_MAX]);
            lp3_param_db.rpst[DDC_PROG] = getRandInterval(lp3_param_db.rpst[DDC_MIN],lp3_param_db.rpst[DDC_MAX]);
            lp3_param_db.rcd[DDC_PROG] = getRandInterval(lp3_param_db.rcd[DDC_MIN],lp3_param_db.rcd[DDC_MAX]);
            lp3_param_db.xsr[DDC_PROG] = getRandInterval(lp3_param_db.xsr[DDC_MIN],lp3_param_db.xsr[DDC_MAX]);
            lp3_param_db.zqreset[DDC_PROG] = getRandInterval(lp3_param_db.zqreset[DDC_MIN],lp3_param_db.zqreset[DDC_MAX]);
            lp3_param_db.cke[DDC_PROG] = getRandInterval(lp3_param_db.cke[DDC_MIN],lp3_param_db.cke[DDC_MAX]);
            lp3_param_db.wtr[DDC_PROG] = getRandInterval(lp3_param_db.wtr[DDC_MIN],lp3_param_db.wtr[DDC_MAX]);
            lp3_param_db.wpre[DDC_PROG] = getRandInterval(lp3_param_db.wpre[DDC_MIN],lp3_param_db.wpre[DDC_MAX]);
            lp3_param_db.bl[DDC_PROG] = getRandInterval(lp3_param_db.bl[DDC_MIN],lp3_param_db.bl[DDC_MAX]);
            lp3_param_db.wl[DDC_PROG] = getRandInterval(lp3_param_db.wl[DDC_MIN],lp3_param_db.wl[DDC_MAX]);
            lp3_param_db.faw[DDC_PROG] = getRandInterval(lp3_param_db.faw[DDC_MIN],lp3_param_db.faw[DDC_MAX]);
            lp3_param_db.zqinit[DDC_PROG] = getRandInterval(lp3_param_db.zqinit[DDC_MIN],lp3_param_db.zqinit[DDC_MAX]);
            lp3_param_db.rl[DDC_PROG] = getRandInterval(lp3_param_db.rl[DDC_MIN],lp3_param_db.rl[DDC_MAX]);
            lp3_param_db.wr[DDC_PROG] = getRandInterval(lp3_param_db.wr[DDC_MIN],lp3_param_db.wr[DDC_MAX]);
            lp3_param_db.rcab[DDC_PROG] = getRandInterval(lp3_param_db.rcab[DDC_MIN],lp3_param_db.rcab[DDC_MAX]);
            lp3_param_db.rlat[DDC_PROG] = getRandInterval(lp3_param_db.rlat[DDC_MIN],lp3_param_db.rlat[DDC_MAX]);
            lp3_param_db.rppb[DDC_PROG] = getRandInterval(lp3_param_db.rppb[DDC_MIN],lp3_param_db.rppb[DDC_MAX]);
            lp3_param_db.sr[DDC_PROG] = getRandInterval(lp3_param_db.sr[DDC_MIN],lp3_param_db.sr[DDC_MAX]);
            lp3_param_db.mrri[DDC_PROG] = getRandInterval(lp3_param_db.mrri[DDC_MIN],lp3_param_db.mrri[DDC_MAX]);
            lp3_param_db.mrw[DDC_PROG] = getRandInterval(lp3_param_db.mrw[DDC_MIN],lp3_param_db.mrw[DDC_MAX]);
            lp3_param_db.mrr[DDC_PROG] = getRandInterval(lp3_param_db.mrr[DDC_MIN],lp3_param_db.mrr[DDC_MAX]);
            lp3_param_db.mrd[DDC_PROG] = getRandInterval(lp3_param_db.mrd[DDC_MIN],lp3_param_db.mrd[DDC_MAX]);
            lp3_param_db.ccd[DDC_PROG] = getRandInterval(lp3_param_db.ccd[DDC_MIN],lp3_param_db.ccd[DDC_MAX]);
            lp3_param_db.ras[DDC_PROG] = getRandInterval(lp3_param_db.ras[DDC_MIN],lp3_param_db.ras[DDC_MAX]);
       }else{//LP4
            lp4_param_db.dqsck[DDC_PROG] = getRandInterval(lp4_param_db.dqsck[DDC_MIN],lp4_param_db.dqsck[DDC_MAX]);
            lp4_param_db.ppd[DDC_PROG] = getRandInterval(lp4_param_db.ppd[DDC_MIN],lp4_param_db.ppd[DDC_MAX]);
            lp4_param_db.rrd[DDC_PROG] = getRandInterval(lp4_param_db.rrd[DDC_MIN],lp4_param_db.rrd[DDC_MAX]);
            lp4_param_db.dqs2dq[DDC_PROG] = getRandInterval(lp4_param_db.dqs2dq[DDC_MIN],lp4_param_db.dqs2dq[DDC_MAX]);
            lp4_param_db.rank[DDC_PROG] = getRandInterval(lp4_param_db.rank[DDC_MIN],lp4_param_db.rank[DDC_MAX]);
            lp4_param_db.rfcab[DDC_PROG] = getRandInterval(lp4_param_db.rfcab[DDC_MIN],lp4_param_db.rfcab[DDC_MAX]);
            lp4_param_db.refi[DDC_PROG] = getRandInterval(lp4_param_db.refi[DDC_MIN],lp4_param_db.refi[DDC_MAX]);
            lp4_param_db.rtw[DDC_PROG] = getRandInterval(lp4_param_db.rtw[DDC_MIN],lp4_param_db.rtw[DDC_MAX]);
            lp4_param_db.rtp[DDC_PROG] = getRandInterval(lp4_param_db.rtp[DDC_MIN],lp4_param_db.rtp[DDC_MAX]);
            lp4_param_db.dqss[DDC_PROG] = getRandInterval(lp4_param_db.dqss[DDC_MIN],lp4_param_db.dqss[DDC_MAX]);
            lp4_param_db.rfcpb[DDC_PROG] = getRandInterval(lp4_param_db.rfcpb[DDC_MIN],lp4_param_db.rfcpb[DDC_MAX]);
            lp4_param_db.rpab[DDC_PROG] = getRandInterval(lp4_param_db.rpab[DDC_MIN],lp4_param_db.rpab[DDC_MAX]);
            lp4_param_db.zqlatch[DDC_PROG] = getRandInterval(lp4_param_db.zqlatch[DDC_MIN],lp4_param_db.zqlatch[DDC_MAX]);
            lp4_param_db.rcpb[DDC_PROG] = getRandInterval(lp4_param_db.rcpb[DDC_MIN],lp4_param_db.rcpb[DDC_MAX]);
            lp4_param_db.xpd[DDC_PROG] = getRandInterval(lp4_param_db.xpd[DDC_MIN],lp4_param_db.xpd[DDC_MAX]);
            lp4_param_db.ckelpd[DDC_PROG] = getRandInterval(lp4_param_db.ckelpd[DDC_MIN],lp4_param_db.ckelpd[DDC_MAX]);
            lp4_param_db.rpst[DDC_PROG] = getRandInterval(lp4_param_db.rpst[DDC_MIN],lp4_param_db.rpst[DDC_MAX]);
            lp4_param_db.rcd[DDC_PROG] = getRandInterval(lp4_param_db.rcd[DDC_MIN],lp4_param_db.rcd[DDC_MAX]);
            lp4_param_db.xsr[DDC_PROG] = getRandInterval(lp4_param_db.xsr[DDC_MIN],lp4_param_db.xsr[DDC_MAX]);
            lp4_param_db.ccdmw[DDC_PROG] = getRandInterval(lp4_param_db.ccdmw[DDC_MIN],lp4_param_db.ccdmw[DDC_MAX]);
            lp4_param_db.escke[DDC_PROG] = getRandInterval(lp4_param_db.escke[DDC_MIN],lp4_param_db.escke[DDC_MAX]);
            lp4_param_db.zqreset[DDC_PROG] = getRandInterval(lp4_param_db.zqreset[DDC_MIN],lp4_param_db.zqreset[DDC_MAX]);
            lp4_param_db.cke[DDC_PROG] = getRandInterval(lp4_param_db.cke[DDC_MIN],lp4_param_db.cke[DDC_MAX]);
            lp4_param_db.wtr[DDC_PROG] = getRandInterval(lp4_param_db.wtr[DDC_MIN],lp4_param_db.wtr[DDC_MAX]);
            lp4_param_db.rtrrd[DDC_PROG] = getRandInterval(lp4_param_db.rtrrd[DDC_MIN],lp4_param_db.rtrrd[DDC_MAX]);
            lp4_param_db.wpre[DDC_PROG] = getRandInterval(lp4_param_db.wpre[DDC_MIN],lp4_param_db.wpre[DDC_MAX]);
            lp4_param_db.bl[DDC_PROG] = getRandInterval(lp4_param_db.bl[DDC_MIN],lp4_param_db.bl[DDC_MAX]);
            lp4_param_db.mrwckel[DDC_PROG] = getRandInterval(lp4_param_db.mrwckel[DDC_MIN],lp4_param_db.mrwckel[DDC_MAX]);
            lp4_param_db.wl[DDC_PROG] = getRandInterval(lp4_param_db.wl[DDC_MIN],lp4_param_db.wl[DDC_MAX]);
            lp4_param_db.faw[DDC_PROG] = getRandInterval(lp4_param_db.faw[DDC_MIN],lp4_param_db.faw[DDC_MAX]);
            lp4_param_db.cmdcke[DDC_PROG] = getRandInterval(lp4_param_db.cmdcke[DDC_MIN],lp4_param_db.cmdcke[DDC_MAX]);
            lp4_param_db.rl[DDC_PROG] = getRandInterval(lp4_param_db.rl[DDC_MIN],lp4_param_db.rl[DDC_MAX]);
            lp4_param_db.wr[DDC_PROG] = getRandInterval(lp4_param_db.wr[DDC_MIN],lp4_param_db.wr[DDC_MAX]);
            lp4_param_db.ckesr[DDC_PROG] = getRandInterval(lp4_param_db.ckesr[DDC_MIN],lp4_param_db.ckesr[DDC_MAX]);
            lp4_param_db.zqinit[DDC_PROG] = getRandInterval(lp4_param_db.zqinit[DDC_MIN],lp4_param_db.zqinit[DDC_MAX]);
            lp4_param_db.rcab[DDC_PROG] = getRandInterval(lp4_param_db.rcab[DDC_MIN],lp4_param_db.rcab[DDC_MAX]);
            lp4_param_db.rlat[DDC_PROG] = getRandInterval(lp4_param_db.rlat[DDC_MIN],lp4_param_db.rlat[DDC_MAX]);
            lp4_param_db.rppb[DDC_PROG] = getRandInterval(lp4_param_db.rppb[DDC_MIN],lp4_param_db.rppb[DDC_MAX]);
            lp4_param_db.wrwtr[DDC_PROG] = getRandInterval(lp4_param_db.wrwtr[DDC_MIN],lp4_param_db.wrwtr[DDC_MAX]);
            lp4_param_db.sr[DDC_PROG] = getRandInterval(lp4_param_db.sr[DDC_MIN],lp4_param_db.sr[DDC_MAX]);
            lp4_param_db.mrri[DDC_PROG] = getRandInterval(lp4_param_db.mrri[DDC_MIN],lp4_param_db.mrri[DDC_MAX]);
            lp4_param_db.mrw[DDC_PROG] = getRandInterval(lp4_param_db.mrw[DDC_MIN],lp4_param_db.mrw[DDC_MAX]);
            lp4_param_db.odtlon[DDC_PROG] = getRandInterval(lp4_param_db.odtlon[DDC_MIN],lp4_param_db.odtlon[DDC_MAX]);
            lp4_param_db.odton[DDC_PROG] = getRandInterval(lp4_param_db.odton[DDC_MIN],lp4_param_db.odton[DDC_MAX]);
            lp4_param_db.mrr[DDC_PROG] = getRandInterval(lp4_param_db.mrr[DDC_MIN],lp4_param_db.mrr[DDC_MAX]);
            lp4_param_db.mrd[DDC_PROG] = getRandInterval(lp4_param_db.mrd[DDC_MIN],lp4_param_db.mrd[DDC_MAX]);
            lp4_param_db.ccd[DDC_PROG] = getRandInterval(lp4_param_db.ccd[DDC_MIN],lp4_param_db.ccd[DDC_MAX]);
            lp4_param_db.ras[DDC_PROG] = getRandInterval(lp4_param_db.ras[DDC_MIN],lp4_param_db.ras[DDC_MAX]);
        }
    }
    if(val != DDC_PROG){
        update_ddc_fields(mc, dram_frequency);
    }
}

#ifdef MCU_IP_VERIF

void update_ddc_params_from_yml(){
    uint32_t line_val, prog_data, line_num;
    ddc_c2py_map ddc_param;   
    char line[80]; 
    FILE *fr;            

    /*"rt" means open the file for reading text */
    /* open the file for reading */
    fr = fopen ("ddc_data.bin", "rt");  
    
    if(fr==NULL){
        hw_status("[DDC_YML_PARAMS] Cound not find ddc_data.bin Skipping update_ddc_params_from_yml()\n");
        return;
    }else{
        hw_status("[DDC_YML_PARAMS] Found reg_data.bin, proceeding with update_ddc_params_from_yml()\n");
    }
      
    line_num = 0;
    
    while(fgets(line, 80, fr) != NULL){
        line_val =  (uint32_t)strtol(line, NULL, 2);
        
        if((line_num%3)==0){
            ddc_param = (ddc_c2py_map)line_val;            
        }else if (line_num%3 == 1){
                
            prog_data = line_val;
            
            switch(ddc_param){
                case LP3_DQSCK: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_DQSCK = %0d\n", prog_data); 
                     lp3_param_db.dqsck[DDC_PROG] = prog_data;
                     break;
                case LP3_PPD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_PPD = %0d\n", prog_data); 
                     lp3_param_db.ppd[DDC_PROG] = prog_data;
                     break;
                case LP3_RRD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RRD = %0d\n", prog_data); 
                     lp3_param_db.rrd[DDC_PROG] = prog_data;
                     break;
                case LP3_ZQCS: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_ZQCS = %0d\n", prog_data); 
                     lp3_param_db.zqcs[DDC_PROG] = prog_data;
                     break;
                case LP3_RANK: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RANK = %0d\n", prog_data); 
                     lp3_param_db.rank[DDC_PROG] = prog_data;
                     break;
                case LP3_RFCAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RFCAB = %0d\n", prog_data); 
                     lp3_param_db.rfcab[DDC_PROG] = prog_data;
                     break;
                case LP3_REFI: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_REFI = %0d\n", prog_data); 
                     lp3_param_db.refi[DDC_PROG] = prog_data;
                     break;
                case LP3_ZQCL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_ZQCL = %0d\n", prog_data); 
                     lp3_param_db.zqcl[DDC_PROG] = prog_data;
                     break;
                case LP3_RTP: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RTP = %0d\n", prog_data); 
                     lp3_param_db.rtp[DDC_PROG] = prog_data;
                     break;
                case LP3_DQSQ: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_DQSQ = %0d\n", prog_data); 
                     lp3_param_db.dqsq[DDC_PROG] = prog_data;
                     break;
                case LP3_DQSS: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_DQSS = %0d\n", prog_data); 
                     lp3_param_db.dqss[DDC_PROG] = prog_data;
                     break;
                case LP3_RFCPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RFCPB = %0d\n", prog_data); 
                     lp3_param_db.rfcpb[DDC_PROG] = prog_data;
                     break;
                case LP3_RPAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RPAB = %0d\n", prog_data); 
                     lp3_param_db.rpab[DDC_PROG] = prog_data;
                     break;
                case LP3_RCPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RCPB = %0d\n", prog_data); 
                     lp3_param_db.rcpb[DDC_PROG] = prog_data;
                     break;
                case LP3_XPD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_XPD = %0d\n", prog_data); 
                     lp3_param_db.xpd[DDC_PROG] = prog_data;
                     break;
                case LP3_RPST: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RPST = %0d\n", prog_data); 
                     lp3_param_db.rpst[DDC_PROG] = prog_data;
                     break;
                case LP3_RCD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RCD = %0d\n", prog_data); 
                     lp3_param_db.rcd[DDC_PROG] = prog_data;
                     break;
                case LP3_XSR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_XSR = %0d\n", prog_data); 
                     lp3_param_db.xsr[DDC_PROG] = prog_data;
                     break;
                case LP3_ZQRESET: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_ZQRESET = %0d\n", prog_data); 
                     lp3_param_db.zqreset[DDC_PROG] = prog_data;
                     break;
                case LP3_CKE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_CKE = %0d\n", prog_data); 
                     lp3_param_db.cke[DDC_PROG] = prog_data;
                     break;
                case LP3_WTR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_WTR = %0d\n", prog_data); 
                     lp3_param_db.wtr[DDC_PROG] = prog_data;
                     break;
                case LP3_WPRE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_WPRE = %0d\n", prog_data); 
                     lp3_param_db.wpre[DDC_PROG] = prog_data;
                     break;
                case LP3_BL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_BL = %0d\n", prog_data); 
                     lp3_param_db.bl[DDC_PROG] = prog_data;
                     break;
                case LP3_WL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_WL = %0d\n", prog_data); 
                     lp3_param_db.wl[DDC_PROG] = prog_data;
                     break;
                case LP3_FAW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_FAW = %0d\n", prog_data); 
                     lp3_param_db.faw[DDC_PROG] = prog_data;
                     break;
                case LP3_ZQINIT: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_ZQINIT = %0d\n", prog_data); 
                     lp3_param_db.zqinit[DDC_PROG] = prog_data;
                     break;
                case LP3_RL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RL = %0d\n", prog_data); 
                     lp3_param_db.rl[DDC_PROG] = prog_data;
                     break;
                case LP3_WR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_WR = %0d\n", prog_data); 
                     lp3_param_db.wr[DDC_PROG] = prog_data;
                     break;
                case LP3_RCAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RCAB = %0d\n", prog_data); 
                     lp3_param_db.rcab[DDC_PROG] = prog_data;
                     break;
                case LP3_RLAT: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RLAT = %0d\n", prog_data); 
                     lp3_param_db.rlat[DDC_PROG] = prog_data;
                     break;
                case LP3_RPPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RPPB = %0d\n", prog_data); 
                     lp3_param_db.rppb[DDC_PROG] = prog_data;
                     break;
                case LP3_SR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_SR = %0d\n", prog_data); 
                     lp3_param_db.sr[DDC_PROG] = prog_data;
                     break;
                case LP3_MRRI: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_MRRI = %0d\n", prog_data); 
                     lp3_param_db.mrri[DDC_PROG] = prog_data;
                     break;
                case LP3_MRW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_MRW = %0d\n", prog_data); 
                     lp3_param_db.mrw[DDC_PROG] = prog_data;
                     break;
                case LP3_MRR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_MRR = %0d\n", prog_data); 
                     lp3_param_db.mrr[DDC_PROG] = prog_data;
                     break;
                case LP3_MRD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_MRD = %0d\n", prog_data); 
                     lp3_param_db.mrd[DDC_PROG] = prog_data;
                     break;
                case LP3_CCD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_CCD = %0d\n", prog_data); 
                     lp3_param_db.ccd[DDC_PROG] = prog_data;
                     break;
                case LP3_RAS: 
                     hw_status("[DDC_YML_PARAMS] saw param LP3_RAS = %0d\n", prog_data); 
                     lp3_param_db.ras[DDC_PROG] = prog_data;
                     break;
                case LP4_DQSCK: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_DQSCK = %0d\n", prog_data); 
                     lp4_param_db.dqsck[DDC_PROG] = prog_data;
                     lp4_param_db.dqsck[DDC_MICRON] = prog_data;
                     break;
                case LP4_PPD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_PPD = %0d\n", prog_data); 
                     lp4_param_db.ppd[DDC_PROG] = prog_data;
                     lp4_param_db.ppd[DDC_MICRON] = prog_data;
                     break;
                case LP4_RRD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RRD = %0d\n", prog_data); 
                     lp4_param_db.rrd[DDC_PROG] = prog_data;
                     lp4_param_db.rrd[DDC_MICRON] = prog_data;
                     break;
                case LP4_DQS2DQ: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_DQS2DQ = %0d\n", prog_data); 
                     lp4_param_db.dqs2dq[DDC_PROG] = prog_data;
                     lp4_param_db.dqs2dq[DDC_MICRON] = prog_data;
                     break;
                case LP4_RANK: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RANK = %0d\n", prog_data); 
                     lp4_param_db.rank[DDC_PROG] = prog_data;
                     lp4_param_db.rank[DDC_MICRON] = prog_data;
                     break;
                case LP4_RFCAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RFCAB = %0d\n", prog_data); 
                     lp4_param_db.rfcab[DDC_PROG] = prog_data;
                     lp4_param_db.rfcab[DDC_MICRON] = prog_data;
                     break;
                case LP4_REFI: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_REFI = %0d\n", prog_data); 
                     lp4_param_db.refi[DDC_PROG] = prog_data;
                     lp4_param_db.refi[DDC_MICRON] = prog_data;
                     break;
                case LP4_RTW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RTW = %0d\n", prog_data); 
                     lp4_param_db.rtw[DDC_PROG] = prog_data;
                     lp4_param_db.rtw[DDC_MICRON] = prog_data;
                     break;
                case LP4_RTP: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RTP = %0d\n", prog_data); 
                     lp4_param_db.rtp[DDC_PROG] = prog_data;
                     lp4_param_db.rtp[DDC_MICRON] = prog_data;
                     break;
                case LP4_DQSS: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_DQSS = %0d\n", prog_data); 
                     lp4_param_db.dqss[DDC_PROG] = prog_data;
                     lp4_param_db.dqss[DDC_MICRON] = prog_data;
                     break;
                case LP4_RFCPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RFCPB = %0d\n", prog_data); 
                     lp4_param_db.rfcpb[DDC_PROG] = prog_data;
                     lp4_param_db.rfcpb[DDC_MICRON] = prog_data;
                     break;
                case LP4_RPAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RPAB = %0d\n", prog_data); 
                     lp4_param_db.rpab[DDC_PROG] = prog_data;
                     lp4_param_db.rpab[DDC_MICRON] = prog_data;
                     break;
                case LP4_ZQLATCH: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ZQLATCH = %0d\n", prog_data); 
                     lp4_param_db.zqlatch[DDC_PROG] = prog_data;
                     lp4_param_db.zqlatch[DDC_MICRON] = prog_data;
                     break;
                case LP4_RCPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RCPB = %0d\n", prog_data); 
                     lp4_param_db.rcpb[DDC_PROG] = prog_data;
                     lp4_param_db.rcpb[DDC_MICRON] = prog_data;
                     break;
                case LP4_XPD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_XPD = %0d\n", prog_data); 
                     lp4_param_db.xpd[DDC_PROG] = prog_data;
                     lp4_param_db.xpd[DDC_MICRON] = prog_data;
                     break;
                case LP4_CKELPD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CKELPD = %0d\n", prog_data); 
                     lp4_param_db.ckelpd[DDC_PROG] = prog_data;
                     lp4_param_db.ckelpd[DDC_MICRON] = prog_data;
                     break;
                case LP4_RPST: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RPST = %0d\n", prog_data); 
                     lp4_param_db.rpst[DDC_PROG] = prog_data;
                     lp4_param_db.rpst[DDC_MICRON] = prog_data;
                     break;
                case LP4_RCD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RCD = %0d\n", prog_data); 
                     lp4_param_db.rcd[DDC_PROG] = prog_data;
                     lp4_param_db.rcd[DDC_MICRON] = prog_data;
                     break;
                case LP4_XSR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_XSR = %0d\n", prog_data); 
                     lp4_param_db.xsr[DDC_PROG] = prog_data;
                     lp4_param_db.xsr[DDC_MICRON] = prog_data;
                     break;
                case LP4_CCDMW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CCDMW = %0d\n", prog_data); 
                     lp4_param_db.ccdmw[DDC_PROG] = prog_data;
                     lp4_param_db.ccdmw[DDC_MICRON] = prog_data;
                     break;
                case LP4_ESCKE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ESCKE = %0d\n", prog_data); 
                     lp4_param_db.escke[DDC_PROG] = prog_data;
                     lp4_param_db.escke[DDC_MICRON] = prog_data;
                     break;
                case LP4_ZQRESET: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ZQRESET = %0d\n", prog_data); 
                     lp4_param_db.zqreset[DDC_PROG] = prog_data;
                     lp4_param_db.zqreset[DDC_MICRON] = prog_data;
                     break;
                case LP4_CKE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CKE = %0d\n", prog_data); 
                     lp4_param_db.cke[DDC_PROG] = prog_data;
                     lp4_param_db.cke[DDC_MICRON] = prog_data;
                     break;
                case LP4_WTR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_WTR = %0d\n", prog_data); 
                     lp4_param_db.wtr[DDC_PROG] = prog_data;
                     lp4_param_db.wtr[DDC_MICRON] = prog_data;
                     break;
                case LP4_RTRRD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RTRRD = %0d\n", prog_data); 
                     lp4_param_db.rtrrd[DDC_PROG] = prog_data;
                     lp4_param_db.rtrrd[DDC_MICRON] = prog_data;
                     break;
                case LP4_WPRE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_WPRE = %0d\n", prog_data); 
                     lp4_param_db.wpre[DDC_PROG] = prog_data;
                     lp4_param_db.wpre[DDC_MICRON] = prog_data;
                     break;
                case LP4_BL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_BL = %0d\n", prog_data); 
                     lp4_param_db.bl[DDC_PROG] = prog_data;
                     lp4_param_db.bl[DDC_MICRON] = prog_data;
                     break;
                case LP4_MRWCKEL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_MRWCKEL = %0d\n", prog_data); 
                     lp4_param_db.mrwckel[DDC_PROG] = prog_data;
                     lp4_param_db.mrwckel[DDC_MICRON] = prog_data;
                     break;
                case LP4_WL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_WL = %0d\n", prog_data); 
                     lp4_param_db.wl[DDC_PROG] = prog_data;
                     lp4_param_db.wl[DDC_MICRON] = prog_data;
                     break;
                case LP4_FAW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_FAW = %0d\n", prog_data); 
                     lp4_param_db.faw[DDC_PROG] = prog_data;
                     lp4_param_db.faw[DDC_MICRON] = prog_data;
                     break;
                case LP4_CMDCKE: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CMDCKE = %0d\n", prog_data); 
                     lp4_param_db.cmdcke[DDC_PROG] = prog_data;
                     lp4_param_db.cmdcke[DDC_MICRON] = prog_data;
                     break;
                case LP4_RL: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RL = %0d\n", prog_data); 
                     lp4_param_db.rl[DDC_PROG] = prog_data;
                     lp4_param_db.rl[DDC_MICRON] = prog_data;
                     break;
                case LP4_WR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_WR = %0d\n", prog_data); 
                     lp4_param_db.wr[DDC_PROG] = prog_data;
                     lp4_param_db.wr[DDC_MICRON] = prog_data;
                     break;
                case LP4_CKESR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CKESR = %0d\n", prog_data); 
                     lp4_param_db.ckesr[DDC_PROG] = prog_data;
                     lp4_param_db.ckesr[DDC_MICRON] = prog_data;
                     break;
                case LP4_ZQINIT: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ZQINIT = %0d\n", prog_data); 
                     lp4_param_db.zqinit[DDC_PROG] = prog_data;
                     lp4_param_db.zqinit[DDC_MICRON] = prog_data;
                     break;
                case LP4_RCAB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RCAB = %0d\n", prog_data); 
                     lp4_param_db.rcab[DDC_PROG] = prog_data;
                     lp4_param_db.rcab[DDC_MICRON] = prog_data;
                     break;
                case LP4_RLAT: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RLAT = %0d\n", prog_data); 
                     lp4_param_db.rlat[DDC_PROG] = prog_data;
                     lp4_param_db.rlat[DDC_MICRON] = prog_data;
                     break;
                case LP4_RPPB: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RPPB = %0d\n", prog_data); 
                     lp4_param_db.rppb[DDC_PROG] = prog_data;
                     lp4_param_db.rppb[DDC_MICRON] = prog_data;
                     break;
                case LP4_WRWTR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_WRWTR = %0d\n", prog_data); 
                     lp4_param_db.wrwtr[DDC_PROG] = prog_data;
                     lp4_param_db.wrwtr[DDC_MICRON] = prog_data;
                     break;
                case LP4_SR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_SR = %0d\n", prog_data); 
                     lp4_param_db.sr[DDC_PROG] = prog_data;
                     lp4_param_db.sr[DDC_MICRON] = prog_data;
                     break;
                case LP4_MRRI: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_MRRI = %0d\n", prog_data); 
                     lp4_param_db.mrri[DDC_PROG] = prog_data;
                     lp4_param_db.mrri[DDC_MICRON] = prog_data;
                     break;
                case LP4_MRW: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_MRW = %0d\n", prog_data); 
                     lp4_param_db.mrw[DDC_PROG] = prog_data;
                     lp4_param_db.mrw[DDC_MICRON] = prog_data;
                     break;
                case LP4_ODTLON: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ODTLON = %0d\n", prog_data); 
                     lp4_param_db.odtlon[DDC_PROG] = prog_data;
                     lp4_param_db.odtlon[DDC_MICRON] = prog_data;
                     break;
                case LP4_ODTON: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_ODTON = %0d\n", prog_data); 
                     lp4_param_db.odton[DDC_PROG] = prog_data;
                     lp4_param_db.odton[DDC_MICRON] = prog_data;
                     break;
                case LP4_MRR: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_MRR = %0d\n", prog_data); 
                     lp4_param_db.mrr[DDC_PROG] = prog_data;
                     lp4_param_db.mrr[DDC_MICRON] = prog_data;
                     break;
                case LP4_MRD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_MRD = %0d\n", prog_data); 
                     lp4_param_db.mrd[DDC_PROG] = prog_data;
                     lp4_param_db.mrd[DDC_MICRON] = prog_data;
                     break;
                case LP4_CCD: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_CCD = %0d\n", prog_data); 
                     lp4_param_db.ccd[DDC_PROG] = prog_data;
                     lp4_param_db.ccd[DDC_MICRON] = prog_data;
                     break;
                case LP4_RAS: 
                     hw_status("[DDC_YML_PARAMS] saw param LP4_RAS = %0d\n", prog_data); 
                     lp4_param_db.ras[DDC_PROG] = prog_data;
                     lp4_param_db.ras[DDC_MICRON] = prog_data;
                     break; 
            }
        }
        line_num++;
    }
}

#endif //MCU_IP_VERIF
    
#endif
