//-----------------------------------------------------------------------------
// File: ddc_params.h
// Author : Matthew Pumar<matpumar@microsoft.com>
// Generated on: 2016-06-27 12:44:57.886442
//-----------------------------------------------------------------------------
// Description : AUTOGENERATED HEADER by ddc_timing.py DO NOT MODIFY
//                  
//-----------------------------------------------------------------------------
// Copyright (c) 2015 by Microsoft.
// This model is the confidential and proprietary property of Microsoft and the
// possession or use of this file requires a written license from Microsoft.
//-----------------------------------------------------------------------------

#ifndef _DDC_PARAMS_H_
#define _DDC_PARAMS_H_

#define DDC_MIN     0
#define DDC_TYP     1
#define DDC_MAX     2
#define DDC_REG     3
#define DDC_PROG    4
#define DDC_MICRON  5
#define DDC_RAND    6

typedef struct{
   uint32_t dqsck[5];
   uint32_t ppd[5];
   uint32_t rrd[5];
   uint32_t zqcs[5];
   uint32_t rank[5];
   uint32_t rfcab[5];
   uint32_t refi[5];
   uint32_t zqcl[5];
   uint32_t rtp[5];
   uint32_t dqsq[5];
   uint32_t dqss[5];
   uint32_t rfcpb[5];
   uint32_t rpab[5];
   uint32_t rcpb[5];
   uint32_t xpd[5];
   uint32_t rpst[5];
   uint32_t rcd[5];
   uint32_t xsr[5];
   uint32_t zqreset[5];
   uint32_t cke[5];
   uint32_t wtr[5];
   uint32_t wpre[5];
   uint32_t bl[5];
   uint32_t wl[5];
   uint32_t faw[5];
   uint32_t zqinit[5];
   uint32_t rl[5];
   uint32_t wr[5];
   uint32_t rcab[5];
   uint32_t rlat[5];
   uint32_t rppb[5];
   uint32_t sr[5];
   uint32_t mrri[5];
   uint32_t mrw[5];
   uint32_t mrr[5];
   uint32_t mrd[5];
   uint32_t ccd[5];
   uint32_t ras[5];
} lp3_ddc_params;

typedef struct{
   uint32_t dqsck[6];
   uint32_t ppd[6];
   uint32_t rrd[6];
   uint32_t dqs2dq[6];
   uint32_t rank[6];
   uint32_t rfcab[6];
   uint32_t refi[6];
   uint32_t rtw[6];
   uint32_t rtp[6];
   uint32_t dqss[6];
   uint32_t rfcpb[6];
   uint32_t rpab[6];
   uint32_t zqlatch[6];
   uint32_t rcpb[6];
   uint32_t xpd[6];
   uint32_t ckelpd[6];
   uint32_t rpst[6];
   uint32_t rcd[6];
   uint32_t xsr[6];
   uint32_t ccdmw[6];
   uint32_t escke[6];
   uint32_t zqreset[6];
   uint32_t cke[6];
   uint32_t wtr[6];
   uint32_t rtrrd[6];
   uint32_t wpre[6];
   uint32_t bl[6];
   uint32_t mrwckel[6];
   uint32_t wl[6];
   uint32_t faw[6];
   uint32_t cmdcke[6];
   uint32_t rl[6];
   uint32_t wr[6];
   uint32_t ckesr[6];
   uint32_t zqinit[6];
   uint32_t rcab[6];
   uint32_t rlat[6];
   uint32_t rppb[6];
   uint32_t wrwtr[6];
   uint32_t sr[6];
   uint32_t mrri[6];
   uint32_t mrw[6];
   uint32_t odtlon[6];
   uint32_t odton[6];
   uint32_t mrr[6];
   uint32_t mrd[6];
   uint32_t ccd[6];
   uint32_t ras[6];
} lp4_ddc_params;

typedef enum ddc_c2py_mapping{
    LP3_DQSCK = 21,
    LP3_PPD = 2,
    LP3_RRD = 8,
    LP3_ZQCS = 38,
    LP3_RANK = 34,
    LP3_RFCAB = 14,
    LP3_REFI = 35,
    LP3_ZQCL = 37,
    LP3_RTP = 11,
    LP3_DQSQ = 22,
    LP3_DQSS = 23,
    LP3_RFCPB = 15,
    LP3_RPAB = 5,
    LP3_RCPB = 4,
    LP3_XPD = 19,
    LP3_RPST = 28,
    LP3_RCD = 7,
    LP3_XSR = 20,
    LP3_ZQRESET = 39,
    LP3_CKE = 17,
    LP3_WTR = 16,
    LP3_WPRE = 27,
    LP3_BL = 33,
    LP3_WL = 24,
    LP3_FAW = 10,
    LP3_ZQINIT = 36,
    LP3_RL = 25,
    LP3_WR = 13,
    LP3_RCAB = 3,
    LP3_RLAT = 26,
    LP3_RPPB = 6,
    LP3_SR = 18,
    LP3_MRRI = 32,
    LP3_MRW = 29,
    LP3_MRR = 31,
    LP3_MRD = 30,
    LP3_CCD = 12,
    LP3_RAS = 9,
    LP4_DQSCK = 61,
    LP4_PPD = 48,
    LP4_RRD = 43,
    LP4_DQS2DQ = 63,
    LP4_RANK = 82,
    LP4_RFCAB = 52,
    LP4_REFI = 78,
    LP4_RTW = 84,
    LP4_RTP = 50,
    LP4_DQSS = 62,
    LP4_RFCPB = 53,
    LP4_RPAB = 46,
    LP4_ZQLATCH = 80,
    LP4_RCPB = 42,
    LP4_XPD = 59,
    LP4_CKELPD = 75,
    LP4_RPST = 68,
    LP4_RCD = 44,
    LP4_XSR = 60,
    LP4_CCDMW = 55,
    LP4_ESCKE = 77,
    LP4_ZQRESET = 81,
    LP4_CKE = 57,
    LP4_WTR = 56,
    LP4_RTRRD = 85,
    LP4_WPRE = 67,
    LP4_BL = 83,
    LP4_MRWCKEL = 73,
    LP4_WL = 64,
    LP4_FAW = 49,
    LP4_CMDCKE = 76,
    LP4_RL = 65,
    LP4_WR = 51,
    LP4_CKESR = 74,
    LP4_ZQINIT = 79,
    LP4_RCAB = 41,
    LP4_RLAT = 66,
    LP4_RPPB = 47,
    LP4_WRWTR = 86,
    LP4_SR = 58,
    LP4_MRRI = 72,
    LP4_MRW = 69,
    LP4_ODTLON = 87,
    LP4_ODTON = 88,
    LP4_MRR = 71,
    LP4_MRD = 70,
    LP4_CCD = 54,
    LP4_RAS = 45,
    LP4_DQSCK_NS = 110,
    LP4_PPD_NS = 97,
    LP4_RRD_NS = 92,
    LP4_DQS2DQ_NS = 112,
    LP4_RANK_NS = 131,
    LP4_RFCAB_NS = 101,
    LP4_REFI_NS = 127,
    LP4_RTW_NS = 133,
    LP4_RTP_NS = 99,
    LP4_DQSS_NS = 111,
    LP4_RFCPB_NS = 102,
    LP4_RPAB_NS = 95,
    LP4_ZQLATCH_NS = 129,
    LP4_RCPB_NS = 91,
    LP4_XPD_NS = 108,
    LP4_CKELPD_NS = 124,
    LP4_RPST_NS = 117,
    LP4_RCD_NS = 93,
    LP4_XSR_NS = 109,
    LP4_CCDMW_NS = 104,
    LP4_ESCKE_NS = 126,
    LP4_ZQRESET_NS = 130,
    LP4_CKE_NS = 106,
    LP4_WTR_NS = 105,
    LP4_RTRRD_NS = 134,
    LP4_WPRE_NS = 116,
    LP4_BL_NS = 132,
    LP4_MRWCKEL_NS = 122,
    LP4_WL_NS = 113,
    LP4_FAW_NS = 98,
    LP4_CMDCKE_NS = 125,
    LP4_RL_NS = 114,
    LP4_WR_NS = 100,
    LP4_CKESR_NS = 123,
    LP4_ZQINIT_NS = 128,
    LP4_RCAB_NS = 90,
    LP4_RLAT_NS = 115,
    LP4_RPPB_NS = 96,
    LP4_WRWTR_NS = 135,
    LP4_SR_NS = 107,
    LP4_MRRI_NS = 121,
    LP4_MRW_NS = 118,
    LP4_ODTLON_NS = 136,
    LP4_ODTON_NS = 137,
    LP4_MRR_NS = 120,
    LP4_MRD_NS = 119,
    LP4_CCD_NS = 103,
    LP4_RAS_NS = 94
} ddc_c2py_map;

#endif
